environment:

  matrix:

    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

test_script:
  - "%PYTHON%\\python.exe -m unittest discover thermography/test -v"

branches:
  only:
    - master
    - devel